### ISSUE TITLE
enable compact storage for structs

### ISSUE THREAD

**Issue by johannbarbie** [acebusters/economy#30]
example:
https://github.com/acebusters/economy/blob/develop/contracts/satelites/PullPayment.sol#L16

value and date can go into 1 32byte storage slot, like:
`<28bytes>value<4bytes>date`

implementation effort:
- compacting
- unwrapping
- new boundary checks for values

**Comment by troggy** [comment]
I don't see any gas savings when using `mapping(addess => uint)` instead of `mapping(address => Payment)`. Not worth the hassle. Am I missing something?

**Comment by troggy** [comment]
@johannbarbie or this is about moving pull payments to Storage contract?

**Comment by johannbarbie** [comment]
nope, not about storage contract.
now `Payment` is taking 64 bytes, by packing the 2 dates into 1, we could reduce to 32bytes, no?

**Comment by troggy** [comment]
I thought so too. I played with it in Remix and seems not to be true. Probably because conversions from base uint256 take gas too.

**Comment by troggy** [comment]
> I don't see any gas savings when using mapping(addess => uint) instead of mapping(address => Payment)

Sorry. There is a difference. I was talking about using struct that supposed to be packed into 32 bytes
